% Scheduling request (Initial scheduling)

clear; clc; close all;

reqType = "INIT";
agentId = 0;

% robots = struct("robotId", {1, 2, 3, 4, 5, 6}, "posx", {0, 0, 0, 0, 0, 0}, "posy", ...
%     {0, 0, 0, 0, 0, 0}, "curTargetx", {0, 0, 0, 0, 0, 0}, "curTargety", {0, 0, 0, 0, 0, 0}, ...
%     "curTargetTheta", {0, 0, 0, 0, 0, 0}, "prevTargetx", {0, 0, 0, 0, 0, 0}, ...
%     "prevTargety", {0, 0, 0, 0, 0 ,0}, "prevTargetTheta", {0, 0, 0, 0, 0, 0});

% robots = struct("robotId", {1, 2, 3, 4, 5}, "posx", {0, 0, 0, 0, 0}, "posy", ...
%     {0, 0, 0, 0, 0}, "curTargetx", {0, 0, 0, 0, 0}, "curTargety", {0, 0, 0, 0, 0}, ...
%     "curTargetTheta", {0, 0, 0, 0, 0}, "prevTargetx", {0, 0, 0, 0, 0}, ...
%     "prevTargety", {0, 0, 0, 0, 0}, "prevTargetTheta", {0, 0, 0, 0, 0});

% robots = struct("robotId", {5, 3, 200, 100}, "posx", {0, 0, 0, 0}, "posy", ...
%     {0, 0, 0, 0}, "curTargetx", {0, 0, 0, 0}, "curTargety", {0, 0, 0, 0}, ...
%     "curTargetTheta", {0, 0, 0, 0}, "prevTargetx", {0, 0, 0, 0}, ...
%     "prevTargety", {0, 0, 0, 0}, "prevTargetTheta", {0, 0, 0, 0});

% robots = struct("robotId", {1, 2, 3}, "posx", {0, 0, 0}, "posy", ...
%     {0, 0, 0}, "curTargetx", {0, 0, 0}, "curTargety", {0, 0, 0}, ...
%     "curTargetTheta", {0, 0, 0}, "prevTargetx", {0, 0, 0}, ...
%     "prevTargety", {0, 0, 0}, "prevTargetTheta", {0, 0, 0});

% robots = struct("robotId", {1, 2}, "posx", {0, 0}, "posy", ...
%     {0, 0}, "curTargetx", {0, 0}, "curTargety", {0, 0}, ...
%     "curTargetTheta", {0, 0}, "prevTargetx", {0, 0}, ...
%     "prevTargety", {0, 0}, "prevTargetTheta", {0, 0});

robots = struct("robotId", {1}, "posx", {0}, "posy", ...
    {0}, "curTargetx", {0}, "curTargety", {0}, ...
    "curTargetTheta", {0}, "prevTargetx", {0}, ...
    "prevTargety", {0}, "prevTargetTheta", {0});

S = struct("reqType", reqType, "agentId", agentId, "posx", ...
    0, "posy", 0, "robots", robots);
s = jsonencode(S);

% 1대에서만 수행
if(size(robots, 2) == 1)
    idx = strfind(s, "{");
    s = insertBefore(s, idx(2), "[");
    idx = strfind(s, "}");
    s = insertAfter(s, idx(1), "]");
end

% Create mqtt connection.
myMQTT = mqtt('tcp://192.168.0.8', 'Port', 1883);
% myMQTT = mqtt('tcp://220.81.76.111', 'Port', 1883);

% Create topic and message.
topic = '/mams/ph/scheduler/req';
message = s;

% Publish a message to a topic.
publish(myMQTT, topic, message, 'Qos', 0);