%#function 
%#function Func_fovPathPlanning
%#function KWMapCoverage
%#function KWcalcMapCoverage
%#function KWcontactCell
%#function KWdataPreProcessing
%#function KWdataPreProcessing2
%#function KWgenerateRobotPose
%#function KWloadSensorParam
%#function KWvisualizeRobot
%#function Rescheduler
%#function bwlabel
%#function close
%#function fliplr
%#function gpuArray
%#function graph.graph
%#function imagesc
%#function imclose
%#function imopen
%#function imread
%#function imresize
%#function imshow
%#function int2str
%#function kron
%#function kw_BWfilter
%#function kw_CBGA
%#function kw_cellDecomposition
%#function kw_dispCoveragePercent
%#function kw_greedyCoverage
%#function kw_imshow
%#function kw_point2ind
%#function kw_sensing_greedy
%#function linspace
%#function mqtt
%#function num2cell
%#function num2str
%#function publish
%#function re_onewaypath
%#function region_assign
%#function rgb2gray
%#function scheduling_response
%#function strcat
%#function strel
%#function sub2ind
%#function unique
%#function wx_to_xi
%#function wy_to_yi
